name: geesenet-sweep-all-data
method: bayes
metric:
  name: val_loss
  goal: minimize
parameters:
  layers:
    min: 6
    max: 24
    distribution: int_uniform
  filters:
    min: 16
    max: 64
    distribution: int_uniform
  dataset_path:
    value: '../input/hungry-geese-episodes-created-by-self-play/hungry-geese-self-play/'
  n_epochs:
    value: 11
  chunk_size:
    min: 500
    max: 1000
  chunk_num:
    value: 1
  val_size:
    value: 100
