# optuna_config_hungry_geese.yaml
description: optuna on launch demo
# a basic training job to run
job: your-entity/your-project/job-https___github.com_nejumi_hungry-geese-demo_src_training.py:latest
run_cap: 5
metric:
  name: val_loss
  goal: minimize

scheduler:
  job: wandb/sweep-jobs/job-optuna-sweep-scheduler:latest
  resource: local-container  # required for scheduler jobs sourced from images
  num_workers: 1  # number of concurrent runs
  settings:
    sampler:
      type: TPESampler
      n_startup_trials: 3
    pruner:
      type: PercentilePruner
      args:
        percentile: 25.0  # kill 75% of runs
        n_warmup_steps: 10  # pruning disabled for first x steps

parameters:
  data_folder:
    values:
      - ./episodes
    distribution: categorical
  chunk_size:
    max: 3000
    min: 100
    distribution: int_uniform
  batch_size:
    max: 2048
    min: 64
    distribution: int_uniform
  chunk_num:
    max: 11
    min: 1
    distribution: int_uniform
  n_epochs:
    max: 11
    min: 1
    distribution: int_uniform
  project:
    values:
      - hungry-geeese-imitation-learning
    distribution: categorical
  filters:
    max: 128
    min: 4
    distribution: int_uniform
  layers:
    max: 64
    min: 4
    distribution: int_uniform